#!/bin/bash
set -e

# ============================================================================
# iSH-ARM64 static library build for the Cuplivo iOS Linux sandbox
# ============================================================================
# Builds libish.a / libish_emu.a / libfakefs.a (arm64, iphoneos) from the
# OpenMinis ish-arm64 fork, which emulates an aarch64 Linux userland inside
# the app process (asbestos engine = threaded interpreter, no JIT, App Store
# safe). Adapted from OpenMinis/deps/build_ish.sh.
#
# Requirements (macOS only):
#   - Xcode command line tools (xcrun iphoneos SDK)
#   - meson and ninja (brew install meson ninja; meson ships ninja as a dep)
#   - LLVM/Clang (brew install llvm) — required for the guest VDSO
#   - lld (brew install lld; llvm 22+ ships it as a separate formula) —
#     required for the guest VDSO link (-fuse-ld=lld)
#
# Usage:
#   ios/sandbox/build_ish.sh [clean]
#
# Output (gitignored; regenerated here or in CI before `flutter build ios`):
#   ios/sandbox/libs/       libish.a libish_emu.a libfakefs.a
#   ios/sandbox/include/    ish/* headers (+ generated cpu-offsets.h)
#   ios/sandbox/resources/  libvdso.so.elf
#
# The Alpine fakefs rootfs zip is NOT built here — it is generated by
# tools/ios_rootfs/prepare_alpine_fakefs.py and committed to the repo.
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ISH_DIR="$SCRIPT_DIR/ish"
OUTPUT_LIBS="$SCRIPT_DIR/libs"
OUTPUT_INCLUDE="$SCRIPT_DIR/include"
OUTPUT_RESOURCES="$SCRIPT_DIR/resources"

# Pinned revision of https://github.com/OpenMinis/ish-arm64 (master).
ISH_REPO="https://github.com/OpenMinis/ish-arm64.git"
ISH_SHA="de124dd66124a15239cea1465164f74980ada245"

ARCHS="arm64"
IOS_DEPLOYMENT_TARGET="14.0"
BUILD_TYPE="${BUILD_TYPE:-release}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log_info()    { echo -e "${BLUE}[ish-build]${NC} $1"; }
log_success() { echo -e "${GREEN}[ish-build]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[ish-build]${NC} $1"; }
log_error()   { echo -e "${RED}[ish-build]${NC} $1"; exit 1; }

clean_build() {
    log_info "Cleaning build artifacts..."
    rm -rf "$ISH_DIR/build-ios" "$OUTPUT_LIBS" "$OUTPUT_INCLUDE"
    rm -f "$OUTPUT_RESOURCES/libvdso.so.elf"
    log_success "Clean completed (ish checkout kept)"
}

check_prerequisites() {
    command -v python3 >/dev/null 2>&1 || log_error "python3 is required"
    command -v meson >/dev/null 2>&1 || log_error "meson is required (pip3 install meson)"
    command -v ninja >/dev/null 2>&1 || log_error "ninja is required (brew install ninja)"
    xcode-select -p >/dev/null 2>&1 || log_error "Xcode command line tools required"

    LLVM_CLANG=""
    for clang_path in "/opt/homebrew/opt/llvm/bin/clang" "/usr/local/opt/llvm/bin/clang" "/opt/local/bin/clang"; do
        if [ -x "$clang_path" ]; then LLVM_CLANG="$clang_path"; break; fi
    done
    [ -n "$LLVM_CLANG" ] || log_error "LLVM clang not found (brew install llvm) — needed for the guest VDSO"
    log_info "LLVM clang: $LLVM_CLANG"
    # Expose lld for the VDSO link (-fuse-ld=lld)
    export PATH="$(dirname "$LLVM_CLANG"):$PATH"
    # llvm 22+ no longer bundles lld (separate formula: brew install lld)
    command -v ld.lld >/dev/null 2>&1 || log_error "ld.lld not found (brew install lld) — needed for the guest VDSO link (-fuse-ld=lld)"
    log_info "ld.lld: $(command -v ld.lld)"
}

fetch_ish() {
    if [ -f "$ISH_DIR/.cuplivo-ish-sha" ] && [ "$(cat "$ISH_DIR/.cuplivo-ish-sha")" = "$ISH_SHA" ]; then
        log_info "ish-arm64 checkout up to date (${ISH_SHA:0:12})"
        return
    fi
    log_info "Fetching $ISH_REPO @ ${ISH_SHA:0:12}..."
    rm -rf "$ISH_DIR"
    mkdir -p "$ISH_DIR"
    git init -q "$ISH_DIR"
    git -C "$ISH_DIR" remote add origin "$ISH_REPO"
    git -C "$ISH_DIR" fetch -q --depth 1 origin "$ISH_SHA"
    git -C "$ISH_DIR" checkout -q FETCH_HEAD
    echo "$ISH_SHA" > "$ISH_DIR/.cuplivo-ish-sha"
    log_success "ish-arm64 checked out"
}

setup_cross_compile() {
    BUILD_DIR="$ISH_DIR/build-ios"
    mkdir -p "$BUILD_DIR"
    IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
    CROSS_FILE="$BUILD_DIR/ios-cross.txt"
    cat > "$CROSS_FILE" << EOF
[binaries]
c = ['clang', '-arch', '$ARCHS', '-isysroot', '$IOS_SDK', '-miphoneos-version-min=$IOS_DEPLOYMENT_TARGET']
ar = 'ar'
strip = 'strip'
pkg-config = 'false'

[host_machine]
system = 'darwin'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[built-in options]
c_args = []
c_link_args = ['-L$IOS_SDK/usr/lib']

[properties]
needs_exe_wrapper = true
sys_root = '$IOS_SDK'
library_dirs = ['$IOS_SDK/usr/lib']
EOF
    log_success "Cross-compilation file created (SDK: $IOS_SDK)"
}

build_ish() {
    BUILD_DIR="$ISH_DIR/build-ios"
    CROSS_FILE="$BUILD_DIR/ios-cross.txt"

    # meson resolves the source directory from cwd (or an explicit second
    # positional); run from $ISH_DIR so `meson setup "$BUILD_DIR"` works
    # (mirrors OpenMinis/deps/build_ish.sh).
    cd "$ISH_DIR"

    if [ ! -f "$BUILD_DIR/build.ninja" ]; then
        log_info "Configuring meson build ($BUILD_TYPE)..."
        meson setup "$BUILD_DIR" \
            --cross-file "$CROSS_FILE" \
            --buildtype="$BUILD_TYPE" \
            -Dlog="" \
            -Dlog_handler=nslog \
            -Dkernel=ish \
            -Dengine=asbestos \
            -Dguest_arch=arm64
    else
        meson configure "$BUILD_DIR" --buildtype="$BUILD_TYPE"
    fi

    log_info "Building static libraries..."
    ninja -C "$BUILD_DIR" libish.a libish_emu.a libfakefs.a

    log_info "Building guest VDSO..."
    ninja -C "$BUILD_DIR" vdso/arm64/libvdso.so.elf
    if [ ! -s "$BUILD_DIR/vdso/arm64/libvdso.so.elf" ]; then
        log_error "VDSO is empty — LLVM/clang with lld is required (brew install llvm lld)"
    fi
    log_success "Libraries built"

    cd "$SCRIPT_DIR"
}

copy_outputs() {
    BUILD_DIR="$ISH_DIR/build-ios"
    mkdir -p "$OUTPUT_LIBS" "$OUTPUT_RESOURCES"
    mkdir -p "$OUTPUT_INCLUDE/ish/emu" "$OUTPUT_INCLUDE/ish/kernel" "$OUTPUT_INCLUDE/ish/fs" \
             "$OUTPUT_INCLUDE/ish/fs/proc" "$OUTPUT_INCLUDE/ish/util" "$OUTPUT_INCLUDE/ish/platform" \
             "$OUTPUT_INCLUDE/ish/asbestos"

    cp "$BUILD_DIR/libish.a" "$BUILD_DIR/libish_emu.a" "$BUILD_DIR/libfakefs.a" "$OUTPUT_LIBS/"
    cp "$BUILD_DIR/vdso/arm64/libvdso.so.elf" "$OUTPUT_RESOURCES/"

    cp "$ISH_DIR/debug.h" "$ISH_DIR/misc.h" "$ISH_DIR/xX_main_Xx.h" "$OUTPUT_INCLUDE/ish/"
    cp "$ISH_DIR"/emu/*.h "$OUTPUT_INCLUDE/ish/emu/"
    cp "$ISH_DIR"/kernel/*.h "$OUTPUT_INCLUDE/ish/kernel/"
    cp "$ISH_DIR"/fs/*.h "$OUTPUT_INCLUDE/ish/fs/"
    [ -d "$ISH_DIR/fs/proc" ] && cp "$ISH_DIR"/fs/proc/*.h "$OUTPUT_INCLUDE/ish/fs/proc/" 2>/dev/null || true
    cp "$ISH_DIR"/util/*.h "$OUTPUT_INCLUDE/ish/util/" 2>/dev/null || true
    cp "$ISH_DIR"/platform/*.h "$OUTPUT_INCLUDE/ish/platform/"
    cp "$ISH_DIR"/asbestos/*.h "$OUTPUT_INCLUDE/ish/asbestos/"
    mkdir -p "$OUTPUT_INCLUDE/ish/asbestos/guest-arm64/gadgets-aarch64"
    cp "$ISH_DIR"/asbestos/guest-arm64/gadgets-aarch64/*.h \
       "$OUTPUT_INCLUDE/ish/asbestos/guest-arm64/gadgets-aarch64/" 2>/dev/null || true
    cp "$ISH_DIR"/asbestos/gadgets-generic.h "$OUTPUT_INCLUDE/ish/asbestos/" 2>/dev/null || true
    mkdir -p "$OUTPUT_INCLUDE/ish/emu/arch/arm64" "$OUTPUT_INCLUDE/ish/kernel/arch/arm64"
    cp "$ISH_DIR"/emu/arch/arm64/*.h "$OUTPUT_INCLUDE/ish/emu/arch/arm64/" 2>/dev/null || true
    cp "$ISH_DIR"/kernel/arch/arm64/*.h "$OUTPUT_INCLUDE/ish/kernel/arch/arm64/" 2>/dev/null || true
    [ -f "$BUILD_DIR/cpu-offsets.h" ] && cp "$BUILD_DIR/cpu-offsets.h" "$OUTPUT_INCLUDE/ish/"
    if [ -f "$ISH_DIR/deps/config.h" ]; then
        mkdir -p "$OUTPUT_INCLUDE/ish/deps"
        cp "$ISH_DIR/deps/config.h" "$OUTPUT_INCLUDE/ish/deps/"
    fi
    log_success "Outputs copied to $OUTPUT_LIBS, $OUTPUT_INCLUDE, $OUTPUT_RESOURCES"
}

print_summary() {
    echo ""
    echo "============================================================"
    log_success "iSH-ARM64 build complete"
    echo "============================================================"
    ls -lh "$OUTPUT_LIBS"/*.a 2>/dev/null || echo "  (none)"
    echo ""
    echo "Xcode links these via LIBRARY_SEARCH_PATHS/OTHER_LDFLAGS in"
    echo "ios/Runner.xcodeproj; no further action needed."
    echo "============================================================"
}

main() {
    echo ""
    echo "============================================================"
    echo "  Cuplivo iOS sandbox: iSH-ARM64 static library builder"
    echo "  Guest arch: arm64 (aarch64 Linux userland emulation)"
    echo "============================================================"
    echo ""
    if [ "$1" == "clean" ]; then clean_build; exit 0; fi
    check_prerequisites
    fetch_ish
    setup_cross_compile
    build_ish
    copy_outputs
    print_summary
}

main "$@"
