import 'dart:async';
import 'dart:io' show Platform;

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../models/assistant.dart';
import '../models/conversation.dart';
import 'proactive_care_conversation_policy.dart';

/// iOS scheduler for proactive care.
///
/// iOS cannot run the decision model on a timer, so this scheduler only
/// registers an arrival notification through `app.scheduled_notifications`
/// (the scheduled-tasks channel, whose taps come back through
/// flutter_local_notifications' response bridge). The letter itself is
/// generated by the start/resume catch-up on the next app launch;
/// [arrivalBodyResolver] is the localized line announcing it.
class IosProactiveCareScheduler {
  IosProactiveCareScheduler({
    MethodChannel? channel,
    DateTime Function()? now,
    this.arrivalBodyResolver,
    bool Function()? isIos,
  }) : _channel = channel ?? const MethodChannel('app.scheduled_notifications'),
       _now = now ?? DateTime.now,
       _isIos = isIos ?? _platformIsIos;

  static const String defaultArrivalBody = 'A letter has arrived.';

  static bool _platformIsIos() => !kIsWeb && Platform.isIOS;

  final MethodChannel _channel;
  final DateTime Function() _now;
  final String? Function()? arrivalBodyResolver;
  final bool Function() _isIos;
  final Map<String, DateTime> _schedules = {};
  bool _disposed = false;

  String get _notificationBody {
    final body = arrivalBodyResolver?.call()?.trim();
    return (body == null || body.isEmpty) ? defaultArrivalBody : body;
  }

  @visibleForTesting
  Map<String, DateTime> get schedules => Map.unmodifiable(_schedules);

  Future<void> attach(
    Future<void> Function(String conversationId, DateTime expectedAt) onFire,
  ) async {}

  Future<void> detach() async {}

  Future<void> sync({
    required Conversation conversation,
    required Assistant? assistant,
  }) async {
    if (_disposed) return;
    final at =
        assistant != null &&
            ProactiveCareConversationPolicy.isEligible(conversation, assistant)
        ? conversation.proactiveCareNextMessageAt
        : null;
    if (at == null || assistant == null || !at.isAfter(_now())) {
      await cancelFor(conversation.id);
    } else {
      _schedules[conversation.id] = at;
      await _scheduleNotification(
        conversationId: conversation.id,
        at: at,
        assistantName: assistant.name,
      );
    }
  }

  Future<void> cancelFor(String conversationId) async {
    _schedules.remove(conversationId);
    try {
      if (_isIos()) {
        await _channel.invokeMethod<void>('cancel', conversationId);
      }
    } catch (e) {
      debugPrint('[IosProactiveCare] cancel failed: $e');
    }
  }

  Future<void> rescheduleAll({
    required List<Conversation> conversations,
    required List<Assistant> assistants,
  }) async {
    if (_disposed) return;
    final pending = ProactiveCareConversationPolicy.pending(
      conversations: conversations,
      assistants: assistants,
      now: _now(),
    );
    _schedules.clear();
    for (final target in pending) {
      _schedules[target.conversation.id] = target.expectedAt;
      await _scheduleNotification(
        conversationId: target.conversation.id,
        at: target.expectedAt,
        assistantName: target.assistant.name,
      );
    }
  }

  Future<void> _scheduleNotification({
    required String conversationId,
    required DateTime at,
    required String assistantName,
  }) async {
    if (!_isIos()) return;
    try {
      await _channel.invokeMethod<bool>('schedule', {
        'runId': conversationId,
        'at': at.millisecondsSinceEpoch,
        'title': assistantName,
        'prepared': false,
        'body': _notificationBody,
        'payload': 'proactive-care:$conversationId',
      });
    } catch (e) {
      debugPrint('[IosProactiveCare] schedule notification failed: $e');
    }
  }

  void dispose() {
    _disposed = true;
    _schedules.clear();
  }
}
