/// The raw SQLite column list of every table LAN sync may write, keyed by table
/// name. It exists so a wire row can never steer SQL: statements are built from
/// these names (which are schema facts) and the row map only supplies values,
/// so a peer cannot smuggle a column or a clause in through a crafted key.
///
/// The chat repository checks the live database against this map at startup,
/// and the forward-compatibility tests compare a migrated database against it —
/// change a table and this must follow.
const Map<String, List<String>> currentSchemaColumns = <String, List<String>>{
  'conversation_rows': [
    'id',
    'title',
    'created_at',
    'updated_at',
    'is_pinned',
    'assistant_id',
    'truncate_index',
    'version_selections_json',
    'summary',
    'last_summarized_message_count',
    'chat_suggestions_json',
    'injected_memory_hash',
    'last_memory_extracted_order',
    'chat_model_provider',
    'chat_model_id',
    'extras_json',
  ],
  'conversation_mcp_server_rows': ['conversation_id', 'server_id', 'ordinal'],
  'message_rows': [
    'id',
    'conversation_id',
    'role',
    'timestamp',
    'model_id',
    'provider_id',
    'total_tokens',
    'is_streaming',
    'reasoning_start_at',
    'reasoning_finished_at',
    'translation',
    'reasoning_segments_json',
    'group_id',
    'version',
    'prompt_tokens',
    'completion_tokens',
    'cached_tokens',
    'duration_ms',
    'message_order',
    'updated_at',
    'sender_id',
    'extras_json',
  ],
  'chat_storage_meta_rows': ['key', 'value'],
  'message_part_rows': [
    'part_id',
    'conversation_id',
    'revision_id',
    'ordinal',
    'kind',
    'payload',
    'created_at',
    'updated_at',
  ],
  'generation_run_rows': [
    'id',
    'conversation_id',
    'target_revision_id',
    'state',
    'state_revision',
    'checkpoint_seq',
    'error_code',
    'created_at',
    'updated_at',
    'terminal_at',
  ],
  'provider_artifact_rows': [
    'conversation_id',
    'revision_id',
    'kind',
    'payload',
    'created_at',
    'updated_at',
  ],
  'asset_rows': [
    'id',
    'content_hash',
    'path',
    'byte_size',
    'width',
    'height',
    'thumbnail_path',
    'created_at',
    'last_referenced_at',
    'extras_json',
  ],
  'message_asset_rows': ['conversation_id', 'revision_id', 'asset_id', 'kind'],
  'asset_gc_rows': ['asset_id', 'not_before', 'attempts', 'generation'],
  'gc_audit_rows': ['id', 'kind', 'entity_id', 'completed_at'],
  'asset_reference_dirty_rows': ['revision_id'],
  'assistant_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'provider_rows': ['provider_key', 'sort_order', 'payload', 'updated_at'],
  'provider_group_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'mcp_server_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'world_book_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'assistant_memory_rows': [
    'id',
    'sort_order',
    'assistant_id',
    'payload',
    'updated_at',
  ],
  'quick_phrase_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'search_service_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'tts_service_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'instruction_injection_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'assistant_tag_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'preference_rows': ['key', 'value', 'updated_at'],
  'memory_entry_rows': [
    'id',
    'sort_order',
    'scope',
    'assistant_id',
    'type',
    'status',
    'content',
    'content_normalized',
    'entry_created_at',
    'entry_updated_at',
    'payload',
    'updated_at',
  ],
  'user_profile_field_rows': ['id', 'sort_order', 'payload', 'updated_at'],
  'message_prompt_rows': [
    'revision_id',
    'conversation_id',
    'payload',
    'carries_memory_snapshot',
    'created_at',
  ],
  'tombstone_rows': ['scope', 'entity_id', 'deleted_at', 'payload'],
  'extension_entity_rows': [
    'kind',
    'id',
    'sort_order',
    'owner_id',
    'payload',
    'updated_at',
  ],
};
